from userbot import bot
from userbot.utils import admin_cmd, sudo_cmd

x = True
@bot.on(admin_cmd(pattern="raid"))
@bot.on(sudo_cmd(pattern="raid", allow_sudo=True))
async def fightbot(event):
       
        await event.delete()
        kek = event.chat_id
        await bot.send_message(kek, "ARE IDHAR AA RANDI KE PILLE TERI MAA KO CHODU :P :V :3")
        await bot.send_message(kek, "MADARCHOD HIJDE KI PAIDAISH TU FIRSE AA GYA GAAND MARWANE :3 LOLX")
        await bot.send_message(kek, "AAJA TERI MAA KE BHOSDE PE SANKIYON KA LODA GHUSED DUN :P :V :3")
        await bot.send_message(kek, "AAJA LIKH TERI MAA KA BUR KAAT LUN :3")
        await bot.send_message(kek, "TYPING TYPING KHELEGA MADARCHOD TERI BEHN CHODU LODUMAL KI AULAAD :3")
        await bot.send_message(kek, "BHAGNA MAT WRNA TERI MAA KO BHAGA BHAGA KR CHODUNGA RAAND KI PAIDAISH :P")
        await bot.send_message(kek, "TERI MAA KI CHOOT BADI SEXY USME GHUSED DUNGA PEPSI RANDI KE BEEJ :P LOLX")
        await bot.send_message(kek, "JO TU LEGA SANKI SE PANGA TERI MAA CHOD DENGE KARKE NANGA :3 :V")
        await bot.send_message(kek, "ABE 2 KODI KI AUKAAT WALE PILLE TERI MAA KO CHODU :V")
        await bot.send_message(kek, "TERI MAA KE BHOSDE ME HAATH DAAL KR TERI MAA KI BACCHEDAANI KHEENCH LUNGA MADARCHOD :3")
        await bot.send_message(kek, "APNI MUMMY KI CHOOT KA RATE BATA CHAL :V")
        await bot.send_message(kek, "ABE PILLE AB LIKH NA MADARCHOD SLOW TYPER :V BADMAASH BANEGA RANDI KE BACCHE :V :P")
        await bot.send_message(kek, "TERI MAA KI KAALI KAALI CHOOT PR MOOT DUNGA :P")
        await bot.send_message(kek, "TERI MAA KE BHOSDE PR AAG LAGA KAR BHAAG JAUNGA HAHAHAHAH :3")
        await bot.send_message(kek, "TERI MAA KE UPR SANKIYON KO CHDWA DUNGA SASTI RANDI KI PAIDAISH :P LOLX")
        await bot.send_message(kek, "BHAAGNA MAT LODU KE BAAL :P")
        await bot.send_message(kek, "SUN KAL TERI MAA CHODI THI AAJ TERI MUMMY CHODUNGA :P")
        await bot.send_message(kek, "SUNA HAI TERI BHEN BADI SEXY HAI USSE PUCH KR BATA AAJ RAAT FREE HAI KYA :P")
        await bot.send_message(kek, "ABE MERE PILLE FEEL KAR GYA RANDI KI PAIDAISH :P HAHAHAHAH")
        await bot.send_message(kek, "TERE MUH PR TATTI BHI NA KRUNGA BHIKAARI CHAPRAASI KI AULAAD :P KEKEKEKEKE :P")
        await bot.send_message(kek, "TERI MAA MERI DARLING HAI APNE BAAP KO ITNI JALDI BHOOL GYA TU,  MERI AULAAD :( :P")
        await bot.send_message(kek, "ARE BHAIYA AAJ CHOD DENGE TUMHARI MAIYA :P")
        await bot.send_message(kek, "SUNO TUMHE SHARAM NHI AATI APNI MUMMY KO ROJ CHUDWANE AA JATE HO :P")
        await bot.send_message(kek, "CHALO AB AA HI GYE HO TO APNI BHEN KI CHOOT KI HAJIRI LAGWAO AAKAR :P")
        await bot.send_message(kek, "ABE LODE KE CHED ITNE ME HI RO GYA MERE JHAANTU JIGAR KE BAAL :P")
        await bot.send_message(kek, "AAJ POORI RAAT TERI MAA KI NONSTOP CHUDAAI KRUNGA RANDI KE :3 :V")
        await bot.send_message(kek, "AAJA LIKH SLOW TYPER PILLE TERI MAA KA BHOSDA FAADU :3 :P")
        await bot.send_message(kek, "ARE RANDI KE BACCHE PAPA BOL MUJHE CHAL MOOH KHOL JALDI :V")
        await bot.send_message(kek, "ME HI TERA REAL BAAP HU BOL QUBOOL HAI MERI NAJAYAZ AULAAD HAI TU RANDI :3")
        await bot.send_message(kek, "TERI MAA KE KAALE KAALE BHOSDE PR AAK THUUUUU :3 KEKEKEKE")
        await bot.send_message(kek, "TERI MAA KI CHOOT FAT GYI KYA BHOSDI KE :3")
        await bot.send_message(kek, "AAJA BETA TERI MAA KA FUDDA KAAT DUN :V :P")
        await bot.send_message(kek, "TERI MAA KE BHOSDE ME GHUSED DUNGA TERI SAARI BADMAASHI :P")
        await bot.send_message(kek, "TERI BHEN KI CHOOT PR FEVI QUICK LAGAKR FIX KR DUNGA PILLE :V")
        await bot.send_message(kek, "TERI MAA KE BHOSDE KO QUICKR PR BECH DUNGA 2 RS ME :V")
        await bot.send_message(kek, "TERI MAA KO 69 POSITION ME CHODUNGA MADARCHOD :V :P")
        await bot.send_message(kek, "FEEL KREGA TU APNE BAAP KO CHAL TAANG UTHA OR GAAND PESH KR RANDI KE BACCHE :P")
        await bot.send_message(kek, "TERI MAA KA BOOR FREE ME BATWA DUNGA YAHAN :V")
        await bot.send_message(kek, "SAALE CHAPRAASI KI PAIDAISH FIGHTER BNEGA RANDI KE BEEJ TERI MAA KA BHOSDA FAADU :3")
        await bot.send_message(kek, "TERI MAA KI CHOOT PR THOOK DUNGA PILLE , PHELE JA OR APNI MAA KE BHOSDE KI SAFAI KARKE AA :V HAHAHAHA")
        await bot.send_message(kek, "TERI BHEN KA BHOSDA DEGA TO BATA ?? :V")
        await bot.send_message(kek, "TERI MAA KO 180 DEGREE ANGLE ME LETA KAR CHODUNGA MADARCHOD BIHAARI KI AULAAD :) :P")
        await bot.send_message(kek, "HAHAHAHAH DEKH TERI MAA KO KESE CHOD RHA HU AAJA MERE PILLE OR AAKAR APNI MAA KI CHOOT ME MERA LODA SET KR :P LOLX")
        await bot.send_message(kek, "SUN MERE PILLE HUM WO HAI JINKE LUND BHI DO HAI , MERI RAAND KE BACCHE :P")
        await bot.send_message(kek, "LE TERI MAA CHOD DI OR TERA DUSRA BHAI NIKAAL DIYA MENE CHAL KHUSH HOJA MADARCHOD OR TAALIYAN BAJA AB :P :V :3")
        await bot.send_message(kek, "ACCHA SUN TERI MAA MERE LODE KE BOHT ACCHE SE CHOOSTI HAI YAAR :V :P <3 HAHAHHA")
        await bot.send_message(kek, "SUN TERI MAA KE MUH ME PESHAAB KAR DUNGA BHOSDIKE RAND KE BACCHE :3 :P")
        await bot.send_message(kek, "DEKH KESE TERI MAA APNI CHOOT UTHA KAR BHAAG RHI :3 KEKEKEKE :)")
        await bot.send_message(kek, "TERE BASS KI BAAT NHI JA OR APNI MAA KO BHEJ :3 :P")
        await bot.send_message(kek, "ACCHA SUN MERE BETE KALAP MATBOR APNI BHEN KA BHOSDA PESH KAR :V")
        await bot.send_message(kek, "TERI MAA BADI KAMAAL KI RANDI HAI YAAR MERA LODA BOHT ACCHE SE CHOOSTI HAI :3 :V")
        await bot.send_message(kek, "IDHAR TERI MAA KE BHOSDE ME WAPAS GHUSEDUN TUJHE :P LOL'X")
        await bot.send_message(kek, "HAHAHAHAHHAAHHAA AB BAITH FEEL KR OR ROLE THODA SA :3")
        await bot.send_message(kek, "SANKI ON FIRE :3 :) <3")
        await bot.send_message(kek, "ABE GAANDU TERI SHAKAL BADI BADSOORAT HAI USPR TATTI BHI NA KRUN ME :( CHEEE CHEE <3")
        await bot.send_message(kek, "DEKH TERI MAA KI CHOOT ME MAINE APNE LUND KI CREAM DAAL DI JA OR JAKAR CHAAT USKO :V :P")
        await bot.send_message(kek, "ABE LANDOORI OR KITNA CHUDEGA ABHI BHI MAUKA HAI BHAAG JA CHAKKE KI AULAAD :P :3")
        await bot.send_message(kek, "TERI GAAND ME POLICE KA DANDA DAAL KR BAWASEER BNA DUNGA BHOSDIKE :) :V")
        await bot.send_message(kek, "ABE BAWASEER KYU APNI MAA CHUDWANE AAYA IDHAR CHAL AB CHUD BAITH KR PYAAR OR ARAAM SE :P HAHAHAHHAH")
        await bot.send_message(kek, "TERI MAA KE BHOSDE ME APNI ACTIVA 5G LEKAR GHUS JAUNGA :3 :P")
        await bot.send_message(kek, "TERI MAA KE BHOSDE ME HOCKEY KHELU MADARCHOD CHINAAL KI PAIDAISH :3 :V")
        await bot.send_message(kek, "TU TELEGRAM PR KYU MAA CHUDWA RHA ABHI APNI MAA KE BHOSDE SE POORA BAHAR TO NIKAL ACCHE SE :P LOLX")
        await bot.send_message(kek, "SUN MADARCHOD, MERE 2 HI TATTE JARA CHOOS KAR BATA MEETHE HAI YA KHATTE :) :V")
        await bot.send_message(kek, "TERI MAA KA BHOSDA FATKE CHAAR HO GYA CHAL APNI MAA KE BHOSDE KO UTHA OR BHAGJA YAHAN SE :V :P")
        await bot.send_message(kek, "SUN MERE BHAAI TERI CHOD DI MENE MAAI :) :P")
        await bot.send_message(kek, "ABE SANKI TERE BAAP HAI APNI MUMMY MT CHUDWA OR BHAGJA YAHAN SE :V :P")
        await bot.send_message(kek, "2 KODI KE AUKAAT WALE PILLE PHELE JAA OR BARABARI KA LEVEL BNA KR AUKAATLESS TATTE :3")
        await bot.send_message(kek, "TERI MAA KO CHODU PATAK PATAK KAR CHAL AB LIKH NA MADARCHOD :3 :V")
        await bot.send_message(kek, "ABE SUAR KI TATTI KHAANE WALE PILLE TU FIGHTER BNEGA JHAANTU :)")
        await bot.send_message(kek, "DEKH TERI MAA TO CHUD GYI CHAL AB APNI BHEN KO PESH KAR")
        await bot.send_message(kek, "ABE SUN NA TERI MAA KA BHOSDA KHARAB HO GYA ISKO MERE LODE SE REPAIR KRNA PADEGA :3")
        await bot.send_message(kek, "AAJA JHUK OR MERA LODA CHOOSLE OR FEEL ME CHOOSNA THODA")
        await bot.send_message(kek, "FIGHTER KI GAAND BNA DUNGA TUJHE SASTI RANDI BHAG JA YAHAN SE :3")
        await bot.send_message(kek, "GANDU APNI MAA MAT CHUDWA OR BHAAGJA YAHAN SE")
        await bot.send_message(kek, "TERI MAA KE BHOSDE KO MERA PRANAAM BOLNA MERE BETE")
        await bot.send_message(kek, "ARE MERI NAJAYAZ AULAAD BADA ZALDI FEEL KR APNE BAAP KO")
        await bot.send_message(kek, "ABE MADARCHOD KAHA BHAAG GYA AB LIKH NA MADARCHOD")
        await bot.send_message(kek, "ABE GANDU MUH KHOL OR PAPA BOL, SANKI ON TABAHIIII <3")
        await bot.send_message(kek, "TERI MAA KE BHOSDE PR KUTTE CHADWADUNGA MADARCHOD")
        await bot.send_message(kek, "KYA HUA TERI MAA KI CHOOT SE KHOON NIKALNE LAGA KYA ITNE ME HI :3 HAHAHAHA")
        await bot.send_message(kek, "CHEE CHEE TERI MAA KE BHOSDE SE SMELL AA RHI GANDI")
        await bot.send_message(kek, "AAJA TERI MAA KI CHOOT CHIKNI KRKE CHODU")
        await bot.send_message(kek, "TU OR TERA KHAANDAN MERE LODE PR GAANDU")
        await bot.send_message(kek, "SUNN MADERCHOD")
        await bot.send_message(kek, "TERI MAA KA BHOSDA")
        await bot.send_message(kek, "BEHEN K LUND")
        await bot.send_message(kek, "TERI MAA KA DUD")
        await bot.send_message(kek, "MERA LAWDA LELE TU AGAR CHAIYE TOH")
        await bot.send_message(kek, "GAANDU")
        await bot.send_message(kek, "CHUTIYA")
        await bot.send_message(kek, "TERI MAA KI CHUT PE JCB CHADHAA DUNGA LOLX KID")
        await bot.send_message(kek, "SAMJHAA LAWDE")
        await bot.send_message(kek, "YA DU TERE GAAND ME TAPAA TAP ?? HAHAHAHA")
        await bot.send_message(kek, "TERI BEHEN MERA ROZ LETI HAI")
        await bot.send_message(kek, "TERI BHEN KE SAATH MMS BANAA CHUKA HU SASTI RANDI")
        await bot.send_message(kek, "TU TO BOHT BADA WALA CHAKKA NIKLA")
        await bot.send_message(kek, "AUR KITNA BOLU BEY MANN BHAR GAYA MERA :3")
        await bot.send_message(kek, "AB BHAAGJA APNI SADI HUI GAAND UTHA KE ! $ANKI ON FIR3 :3")
        
        